#!/usr/bin/python3
print("Content-type: text/html\r\n")
print("Location: http://127.0.0.1/\r\n")
print("StatusCode: 200\r\n")
print("\r\n\r\n")
print("<!DOCTYPE html>")
print("<html>")
print("<head><title>sample html</title></head>")
print("<body>")
print("<h1>hello test.py</h1>")
print("</body></html>")
