name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: unit_test
      run: make unit_test
