name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  googletest:
    runs-on: macos-latast
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: |
        cd config
        make test
