name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mac_compile:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: |
        make
